import Header from "@/components/Header";
import "./globals.css";
// import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/Sidebar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Event Management",
  description: "Generated by create next app",
  keywords: [],
};

export default function RootLayout({ children }) {
  return (
    <html>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
        />
      </head>
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body className="">
        <SidebarProvider>
          <AppSidebar />
          <div
            className="relative h-screen min-h-full float-right transition-all"
            style={{ width: "calc(100% - 0px)" }}
          >
            <Header />
            <main className="w-full p-md-5 bg-gray-50">{children}</main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
